WebEcommerce/Models/Coupon.cs
using System.ComponentModel.DataAnnotations;

namespace WebEcommerce.Models
{
    public class Coupon
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Tên không được để trống")]
        public string Name { get; set; }
        public string? Description { get; set; }
        public DateTime DateStart { get; set; } = DateTime.Now;
        public DateTime DateEnd { get; set; } =DateTime.Now;
        public int Status { get; set; }
        public int Quantity{ get; set; }
        public decimal? Price { get; set; }
        public ICollection<Invoice> Invoices { get; set; }
    }
}

WebEcommerce/Areas/Admin/Controllers/CouponController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebEcommerce.Data;
using WebEcommerce.Models;
using WebEcommerce.ViewModels;
using X.PagedList.Extensions;

namespace WebEcommerce.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CouponController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly INotyfService _notification;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public CouponController(ApplicationDbContext context,INotyfService notyfService, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _notification = notyfService;
            _webHostEnvironment = webHostEnvironment;
        }

        // Hiển thị danh sách mã giảm giá
        [Authorize(Roles = "Admin,Author")]
        [HttpGet]
        public async Task<IActionResult> Index(int? page)
        {
            int pageSize = 5;
            int pageNum = page ?? 1;

            // lấy toàn bộ mã giảm giá trong cơ sở dữ liệu
            var coupons = await _context.Coupons.ToListAsync();
            var listOfCouponVM = coupons.Select(x => new CouponVM()
            {
                Id = x.Id,
                Name = x.Name,
                DateStart = x.DateStart,
                DateEnd = x.DateEnd,
                Quantity = x.Quantity,
                Description = x.Description,
                Price = x.Price,
                Status = x.Status
            });

            var pagedCouponVM= listOfCouponVM.ToPagedList(pageNum, pageSize);
            return View(pagedCouponVM);
        }

        // Thêm mã giảm giá mới (hiển thị form)
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult Create()
        {
            return View(new CouponVM());
        }

        // Xử lý tạo mã giảm giá (lưu vào csdl)
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> Create(CouponVM vm)
        {
            // Kiểm tra tính hợp lệ của dữ liệu
            if (!ModelState.IsValid)
            {
                return View(vm);
            }

            // Tạo một đối tượng Coupon mới từ dữ liệu
            var coupon = new Coupon()
            {
                Name = vm.Name,
                DateStart = vm.DateStart,
                DateEnd = vm.DateEnd.AddDays(7), 
                Description = vm.Description,
                Quantity = vm.Quantity,
                Price = vm.Price,
                Status = vm.Status
            };

            // Lưu coupon vào csdl
            await _context.Coupons.AddAsync(coupon);
            await _context.SaveChangesAsync();
            _notification.Success("Coupon created successfully");
            return RedirectToAction("Index");
        }

        // Cập nhập mã giảm giá (hiển thị form)
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            // Tìm mã giảm giá theo id đã lưu trong csdl
            var coupon = await _context.Coupons.FirstOrDefaultAsync(x => x.Id == id);
            if (coupon == null)
            {
                _notification.Error("coupon not found");
                return View();
            }

            // Hiển thị view với các thuộc tính bên dưới
            var vm = new CouponVM()
            {
                Id = coupon.Id,
                Name = coupon.Name,
                DateStart = coupon.DateStart,
                DateEnd = coupon.DateEnd.AddDays(7),
                Quantity = coupon.Quantity,
                Price = coupon.Price,
                Status = coupon.Status
            };

            return View(vm);
        }

        // Xử lý cập nhật mã giảm giá
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> Edit(CouponVM vm)
        {
            // Kiểm tra tính hợp lệ của dữ liệu
            if (!ModelState.IsValid)
            {
                return View(vm);
            }

            // Tìm mã giảm giá theo ID 
            var coupon = await _context.Coupons.FirstOrDefaultAsync(x => x.Id == vm.Id);
            if (coupon == null)
            {
                _notification.Error("coupon not found");
                return View(vm);
            }

            // Cập nhật các thuộc tính của coupon
            coupon.Name = vm.Name;
            coupon.Description = vm.Description;
            coupon.Price = vm.Price;
            coupon.Quantity = vm.Quantity;
            coupon.Description = vm.Description;
            coupon.Status = vm.Status;
            coupon.DateStart = vm.DateStart;
            coupon.DateEnd = vm.DateEnd;

            //  Cập nhật coupon trong cơ sở dữ liệu
            _context.Coupons.Update(coupon);
            await _context.SaveChangesAsync();
            _notification.Success("Edit successfully");
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            // Tìm mã giảm giá theo id
            var coupon = await _context.Coupons.FirstOrDefaultAsync(x => x.Id == id);
            if (coupon == null)
            {
                _notification.Error("Coupon not found");
                return RedirectToAction("Index");
            }

            // Xóa mã giảm giá khỏi csdl
            _context.Coupons.Remove(coupon);
            await _context.SaveChangesAsync();
            _notification.Success("Coupon deleted successfully");
            return RedirectToAction("Index");
        }
    }
}

WebEcommerce/Areas/Admin/Views/Coupon/Create.cshtml
@model WebEcommerce.ViewModels.CouponVM
@{
    ViewData["Title"] = "Thêm mã giảm giá";
}

<div class="container-fluid">
    <a class="btn btn-primary mb-1" asp-action="Index" asp-controller="Coupon">Go Back</a>
    <div class="card">
        <div class="card-header bg-primary">
            <h4 class="card-title text-white">Thêm mã giảm giá</h4>
        </div>
        <div class="card-body">
            <form asp-action="Create" asp-controller="Coupon" asp-area="Admin" enctype="multipart/form-data">

                <div class="row mb-2">
                    <div class="col-12">
                        <div class="mb-2">
                            <label>Tên</label>
                            <input type="text" asp-for="Name" class="form-control" />
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                        <div class="mb-2">
                            <label>Description</label>
                            <input id="richEditor" type="text" asp-for="Description" class="form-control" />
                            <span asp-validation-for="Description" class="text-danger"></span>
                        </div>
                        <div class="mb-2">
                            <label>Price</label>
                            <input type="number" asp-for="Price" class="form-control" step="0.01" />
                            <span asp-validation-for="Price" class="text-danger"></span>
                        </div>
                        <div class="mb-2">
                            <label>Số lượng</label>
                            <input type="number" asp-for="Quantity" class="form-control"  />
                            <span asp-validation-for="Quantity" class="text-danger"></span>
                        </div>
                        <div class="mb-2">
                            <label for="deliveryDateTime">Ngày thêm mã</label>
                            <input type="datetime-local" asp-for="DateStart" id="deliveryDateTime" class="form-control" min="" />
                            <span asp-validation-for="DateStart" class="text-danger"></span>
                        </div>
                        <div class="mb-2">
                            <label for="deliveryDateTime">Ngày hạn</label>
                            <input type="datetime-local" asp-for="DateEnd" id="deliveryDateTime" class="form-control" min="" />
                            <span asp-validation-for="DateEnd" class="text-danger"></span>
                        </div>
                        <div class="mb-2">
                            <label for="statusId">Tình trạng</label>
                            <select asp-for="Status" class="form-control custom-select" id="status">
                                <option value="1">Hiển thị</option>
                                <option value="2">Hết hạn</option>
                                
                            </select>
                            <span asp-validation-for="Status" class="text-danger"></span>
                        </div>
                    </div>
                    
                </div>

                <div class="mb-2">
                    <button type="submit" class="btn btn-primary w-100">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
    const deliveryDateTimeInput = document.getElementById('deliveryDateTime');
    const now = new Date();
    const localDateTime = new Date(now.getTime() - now.getTimezoneOffset() * 60000).toISOString().slice(0, 16);
    deliveryDateTimeInput.min = localDateTime;
</script>

WebEcommerce/Areas/Admin/Views/Coupon/Edit.cshtml
@model WebEcommerce.ViewModels.CouponVM
@{
    ViewData["Title"] = "Cập nhập mã giảm giá";
}

<div class="container-fluid">
    <a class="btn btn-primary mb-1" asp-action="Index" asp-controller="Coupon">Go Back</a>
    <div class="card">
        <div class="card-header bg-primary">
            <h4 class="card-title text-white">Thêm mã giảm giá</h4>
        </div>
        <div class="card-body">
            <form asp-action="Edit" asp-controller="Coupon" asp-area="Admin" enctype="multipart/form-data">
                <input type="hidden" asp-for="Id" />
                <div class="row mb-2">
                    <div class="col-12">
                        <div class="mb-2">
                            <label>Tên</label>
                            <input type="text" asp-for="Name" class="form-control" />
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                        <div class="mb-2">
                            <label>Description</label>
                            <input id="richEditor" type="text" asp-for="Description" class="form-control" />
                            <span asp-validation-for="Description" class="text-danger"></span>
                        </div>
                        <div class="mb-2">
                            <label>Price</label>
                            <input type="number" asp-for="Price" class="form-control" step="0.01" />
                            <span asp-validation-for="Price" class="text-danger"></span>
                        </div>
                        <div class="mb-2">
                            <label>Số lượng</label>
                            <input type="number" asp-for="Quantity" class="form-control" />
                            <span asp-validation-for="Quantity" class="text-danger"></span>
                        </div>
                        <div class="mb-2">
                            <label for="deliveryDateTime">Ngày thêm mã</label>
                            <input type="datetime-local" asp-for="DateStart" id="deliveryDateTime" class="form-control" min="" />
                            <span asp-validation-for="DateStart" class="text-danger"></span>
                        </div>
                        <div class="mb-2">
                            <label for="deliveryDateTime">Ngày hạn</label>
                            <input type="datetime-local" asp-for="DateEnd" id="deliveryDateTime" class="form-control" min="" />
                            <span asp-validation-for="DateEnd" class="text-danger"></span>
                        </div>
                        <div class="mb-2">
                            <label for="statusId">Tình trạng</label>
                            <select asp-for="Status" class="form-control custom-select" id="status">
                                <option value="1">Hiển thị</option>
                                <option value="2">Hết hạn</option>

                            </select>
                            <span asp-validation-for="Status" class="text-danger"></span>
                        </div>
                    </div>

                </div>

                <div class="mb-2">
                    <button type="submit" class="btn btn-primary w-100">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
    const deliveryDateTimeInput = document.getElementById('deliveryDateTime');
    const now = new Date();
    const localDateTime = new Date(now.getTime() - now.getTimezoneOffset() * 60000).toISOString().slice(0, 16);
    deliveryDateTimeInput.min = localDateTime;
</script>

WebEcommerce/Areas/Admin/Views/Coupon/Index.cshtml
@using X.PagedList
@using X.PagedList.Mvc.Core
@model IPagedList<WebEcommerce.ViewModels.CouponVM>
@{
    ViewData["Title"] = "Danh sách giảm giá";
}

<div class="container-fluid">
    <a class="btn btn-primary mb-1" asp-action="Create" asp-controller="Coupon" asp-area="Admin">Thêm mã giảm giá</a>
    <div class="card">
        <div class="card-header bg-primary">
            <h4 class="card-title text-white">Danh sách mã giảm giá</h4>
        </div>
        <div class="card-body">
            <table class="table table-striped table-hover" id="myTable">
                <thead>
                    <tr>
                        <th>Mã</th>
                        <th>Mô tả</th>
                        <th>Ngày tạo</th>
                        <th>Ngày hạn</th>
                        <th>Tiền</th>
                        <th>Số lượng </th>
                        <th>Tình trạng</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var i in Model)
                    {
                        <tr>
                            
                            <td>@i.Name</td>
                            <td>  @Html.Raw(@i.Description)</td>
                            <td>@i.DateStart</td>
                            <td>@i.DateEnd</td>
                            <td>@WebEcommerce.Common.Common.FormatNumber(i.Price, 0)đ</td>
                            <td>@i.Quantity</td>
                            <td>
                                @if (i.Status == 1)
                                {
                                    <span>Hiển thị</span>
                                }
                                @if (i.Status == 2)
                                {
                                    <span>Hết hạn</span>
                                }
                                
                            </td>
                            <td class="action-buttons">
                                <a class="btn btn-warning btn-sm" asp-area="Admin" asp-controller="Coupon" asp-action="Edit" asp-route-id="@i.Id">Edit</a> |
                                <form class="d-inline" asp-area="Admin" asp-controller="Coupon" asp-action="Delete" asp-route-id="@i.Id" method="post" onsubmit="return confirm('Do you want to delete this coupon?')">
                                    <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                                </form>
                            </td>

                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <div class="card-footer">
            Page @(Model?.PageCount < Model?.PageNumber ? 0 : Model?.PageNumber) of @Model?.PageCount
            @Html.PagedListPager(Model, page => Url.Action("Index",
                     new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }),
                     new PagedListRenderOptions()
            {
                ContainerDivClasses = new List<string> { "coupon", "navigation" },
                UlElementClasses = new List<string> { "pagination" },
                LiElementClasses = new List<string> { "page-item", "page-link" },
                ActiveLiElementClass = "active",

            })
        </div>
    </div>
</div>