WebEcommerce/Models/Invoice.cs
namespace WebEcommerce.Models
{
	public class Invoice
	{
        public int InvoiceId { get; set; }
		public string? ApplicationUserId { get; set; }
        //public int? ShippingId { get; set; }
        public string? Code { get; set; }
        public DateTime? OrderDate { get; set; } = DateTime.Now;
		public DateTime? RequiredDate { get; set; }
		public DateTime? DeliveryDate { get; set; }
		public string? LastName { get; set; }
        public string? FirstName { get; set; }
        public string? PhoneNumber { get; set; }
        public string? Email { get; set; }

        public string? Address { get; set; }
		public string? PaymentMethod { get; set; }
		public string? ShippingMethod { get; set; }
		public decimal? ShippingFee { get; set; }
		public int StatusId { get; set; }
		public string? Notes { get; set; }
        public int? CouponId { get; set; } 
        public Coupon Coupon { get; set; }
        //public Shipping Shipping { get; set; } 
        public virtual ApplicationUser ApplicationUser { get; set; }
        public virtual ICollection<InvoiceDetail> InvoiceDetails { get; set; } = new List<InvoiceDetail>();
    }
}

WebEcommerce/Areas/Admin/Controllers/InvoiceController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebEcommerce.Data;
using WebEcommerce.Models;
using WebEcommerce.ViewModels;
using X.PagedList.Extensions;

namespace WebEcommerce.Areas.Admin.Controllers
{
    [Area("Admin")]

    public class InvoiceController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly INotyfService _notification;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public InvoiceController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment,INotyfService notyfService)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
            _notification = notyfService;
        }
        // Hiển thị danh sách hóa đơn
        [Authorize(Roles = "Admin,Author")]
        [HttpGet]
        public async Task<IActionResult> Index(int? page) 
        {
            int pageSize = 5;
            int pageNum = page ?? 1;
            var invoices = await _context.Invoices
                .Include(i => i.InvoiceDetails) // Bao gồm thông tin hóa đơn chi tiết liên quan
                .ToListAsync();
            var listOfInvoice = invoices.Select(x => new InvoiceVM()
            {
                Id = x.InvoiceId,
                Code = x.Code,
                FirstName = x.FirstName,
                LastName = x.LastName,
                //Price = InvoiceDetail.Price,
                Address = x.Address,
                PhoneNumber = x.PhoneNumber,
                Email = x.Email,
                PaymentMethod = x.PaymentMethod,
                OrderDate = x.OrderDate,
                DeliveryDate = x.DeliveryDate,
                ShippingMethod = x.ShippingMethod,
                ShippingFee = x.ShippingFee,
                StatusId = x.StatusId,
                Notes = x.Notes,
                InvoiceDetailId = x.InvoiceDetails.FirstOrDefault()?.Id

            }).ToList();
            var pagedInvoiceVM = listOfInvoice.ToPagedList(pageNum, pageSize);
            return View(pagedInvoiceVM);
        }
        // Cập nhập hóa đơn
        [Authorize(Roles = "Admin,Author")]
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var invoice = await _context.Invoices.FirstOrDefaultAsync(x => x.InvoiceId == id);
            if(invoice == null)
            {
                _notification.Error("Invoice not found");   
                return View();
            }
            var vm = new InvoiceVM()
            {
                Id = invoice.InvoiceId,
                Code = invoice.Code,
                FirstName = invoice.FirstName,
                LastName = invoice.LastName,
                Address = invoice.Address,
                PhoneNumber = invoice.PhoneNumber,
                Email = invoice.Email,
                PaymentMethod = invoice.PaymentMethod,
                OrderDate = invoice.OrderDate,
                DeliveryDate = invoice.DeliveryDate,
                ShippingMethod = invoice.ShippingMethod,
                ShippingFee = invoice.ShippingFee,
                StatusId = invoice.StatusId,
                Notes = invoice.Notes,
            };
            return View(vm);
        }
        [Authorize(Roles = "Admin,Author")]
        [HttpPost] 
        public async Task<IActionResult> Edit(InvoiceVM vm)
        {
            if (!ModelState.IsValid)
            {
                return View(vm);
            }
            var invoice = await _context.Invoices.FirstOrDefaultAsync(x => x.InvoiceId == vm.Id);
            if (invoice == null)
            {
                _notification.Error("Invoice not found");
                return View(vm);
            }
            invoice.Code = vm.Code;
            invoice.FirstName = vm.FirstName;
            invoice.LastName = vm.LastName;
            //InvoiceDetail.Price = vm.Price;
            invoice.Address = vm.Address;
            invoice.PhoneNumber = vm.PhoneNumber;
            invoice.PaymentMethod = vm.PaymentMethod;
            invoice.OrderDate = vm.OrderDate;
            invoice.DeliveryDate = vm.DeliveryDate;
            invoice.ShippingMethod = vm.ShippingMethod;
            invoice.ShippingFee = vm.ShippingFee;
            invoice.StatusId = vm.StatusId;
            invoice.Notes = vm.Notes;
            _context.Invoices.Update(invoice);
            await _context.SaveChangesAsync();
            _notification.Success("Edit successfully");
            return RedirectToAction("Index");

        }
       // Xóa hóa đơn
       //[Authorize(Roles = "Admin,Author")]
       //[HttpPost]
       // public async Task<IActionResult> Delete(int id)
       // {
       //     var invoice = await _context.Invoices
       //         .Include(i => i.InvoiceDetails) // Include related InvoiceDetails
       //         .FirstOrDefaultAsync(x => x.InvoiceId == id);

       //     if (invoice == null)
       //     {
       //         _notification.Error("Invoice not found");
       //         return RedirectToAction("Index", "Invoice", new { area = "Admin" });
       //     }

       //     // Remove related InvoiceDetails first
       //     if (invoice.InvoiceDetails != null && invoice.InvoiceDetails.Any())
       //     {
       //         _context.InvoiceDetails.RemoveRange(invoice.InvoiceDetails);
       //     }

       //     _context.Invoices.Remove(invoice);
       //     await _context.SaveChangesAsync();

       //     _notification.Success("Delete successfully");
       //     return RedirectToAction("Index");
       // }
        [Authorize(Roles = "Admin,Author")]
        [HttpGet]
        public async Task<IActionResult> Detail(int id)
        {
            // Tìm hóa đơn chi tiết theo ID
            var invoiceDetail = await _context.InvoiceDetails
                .Include(id => id.Invoice) // Bao gồm thông tin hóa đơn liên quan
                .Include(id => id.Product)  // Bao gồm thông tin sản phẩm liên quan
                .FirstOrDefaultAsync(x => x.Id == id);

            if (invoiceDetail == null)
            {
                _notification.Error("Không tìm thấy hóa đơn.");
                return View();
            }

            var vm = new InvoiceDetailVM
            {
                Price = invoiceDetail.Price,
                Quantity = invoiceDetail.Quantity,
                Code = invoiceDetail.Invoice?.Code,
                ProductName = invoiceDetail.Product?.ProductName
            };

            return View(vm); 
        }
    }
}

WebEcommerce/Controllers/InvoiceController.cs
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;
using WebEcommerce.Data;
using WebEcommerce.ViewModels;

namespace WebEcommerce.Controllers
{
    public class InvoiceController : Controller
    {
        private readonly ApplicationDbContext _context;
        public InvoiceController (ApplicationDbContext context)
        {
            _context = context;
        }
        // Theo dõi đơn hàng của người dùng
        public async Task<IActionResult> Tracking()
        {
            // Lấy ID người dùng hiện tại từ claims
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            // Lấy danh sách hóa đơn của người dùng, bao gồm thông tin chi tiết sản phẩm trong từng hóa đơn
            var invoices = await _context.Invoices
                .Where(i => i.ApplicationUserId == userId) // Lọc hóa đơn của người dùng hiện tại
                .Include(i => i.InvoiceDetails)
                .ThenInclude(d => d.Product)
                .ToListAsync();
            // Chuyển đổi dữ liệu hóa đơn thành ViewModel để dễ dàng hiển thị trong View
            var viewModel = invoices.Select(i => new OrderTrackingVM
            {
                InvoiceId = i.InvoiceId,
                Code = i.Code,
                OrderDate = i.OrderDate,
                DeliveryDate = i.DeliveryDate,
                StatusId = i.StatusId,
                Items = i.InvoiceDetails.Select(d => new OrderItemVM
                {
                    ProductName = d.Product.ProductName,
                    Quantity = d.Quantity ?? 0,
                    Price = d.Price ?? 0,
                    Discount = d.Discount
                }).ToList()
            }).ToList();

            return View(viewModel);
        }
    }
}

WebEcommerce/Areas/Admin/Views/Invoice/Detail.cshtml
@model WebEcommerce.ViewModels.InvoiceDetailVM

@{
    ViewData["Title"] = "Chi tiết hóa đơn";
}


<div class="container-fluid">

    <div class="card">
        <div class="card-header bg-primary">
            <h4 class="card-title text-white">Hóa đơn chi tiết</h4>
        </div>
        <div class="card-body">
            <table class="table table-striped table-hover" id="myTable">
                
                <thead>
                    <tr>
                        <th>Mã đơn hàng</th>
                        <th>Tên sản phẩm</th>
                        <th>Giá tiền</th>
                        <th>Số lượng</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>@Model.Code</td>
                        <td>@Model.ProductName</td>
                        <td>@WebEcommerce.Common.Common.FormatNumber(Model.Price, 0)đ</td>
                        <td>@Model.Quantity</td>

                    </tr>

                    

               </tbody>
            </table>
        </div>
        <a asp-action="Index" asp-controller="Invoice" asp-area="Admin" class="btn btn-primary" style="width:10%">Quay lại danh sách hóa đơn</a>

        
    </div>
</div>

WebEcommerce/Areas/Admin/Views/Invoice/Edit.cshtml
@model WebEcommerce.ViewModels.InvoiceVM
@{
    ViewData["Title"] = "Edit Category";
}
<style>
    #deliveryDate {
        width: 100%;
        padding: 10px;
        border-radius: 5px;
        border: 1px solid #ced4da;
        box-shadow: inset 0 1px 2px rgba(0,0,0,0.1);
        font-size: 1rem;
        color: #495057;
        background-color: #fff;
    }

        #deliveryDate:focus {
            border-color: #80bdff;
            outline: 0;
            box-shadow: 0 0 5px rgba(128, 189, 255, 0.5);
        }

</style>
<div class="container-fluid">
    <a class="btn btn-primary mb-1" asp-action="Index" asp-controller="Invoice">Go Back</a>
    <div class="card">
        
        <div class="card-body">
            <form asp-action="Edit" asp-controller="Invoice" asp-area="Admin" enctype="multipart/form-data">
                <input type="hidden" asp-for="Id" />
                
                <div class="row mb-2">
                    <div class="col-12">
                        <div class="mb-2">
                            <label>Mã đơn hàng</label>
                            <input type="text" asp-for="Code" class="form-control" />
                            <span asp-validation-for="Code" class="text-danger"></span>
                        </div>
                        <div class="mb-2">
                            <label>Họ</label>
                            <input type="text" asp-for="LastName" class="form-control" />
                            <span asp-validation-for="LastName" class="text-danger"></span>
                        </div>
                        <div class="mb-2">
                            <label>Tên</label>
                            <input type="text" asp-for="FirstName" class="form-control" />
                            <span asp-validation-for="FirstName" class="text-danger"></span>
                        </div>
                        <div class="mb-2">
                            <label>Số điện thoại</label>
                            <input type="text" asp-for="PhoneNumber" class="form-control" />
                            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                        </div>
                        <div class="mb-2">
                            <label>Email</label>
                            <input type="text" asp-for="Email" class="form-control" />
                            <span asp-validation-for="Email" class="text-danger"></span>
                        </div>
                        <div class="mb-2">
                            <label>Phương thức thanh toán</label>
                            <input type="text" asp-for="PaymentMethod" class="form-control" />
                            <span asp-validation-for="PaymentMethod" class="text-danger"></span>
                        </div>
                        <div class="mb-2">
                            <label for="deliveryDateTime">Ngày và thời gian vận chuyển</label>
                            <input type="datetime-local" asp-for="DeliveryDate" id="deliveryDateTime" class="form-control" min="" />
                            <span asp-validation-for="DeliveryDate" class="text-danger"></span>
                        </div>
                        <div class="mb-2">
                            <label for="statusId">Tình trạng</label>
                            <select asp-for="StatusId" class="form-control custom-select" id="statusId">
                                <option value="1">1</option>
                                <option value="2">2</option>
                                <option value="3">3</option>
                                <option value="4">4</option>
                            </select>
                            <span asp-validation-for="StatusId" class="text-danger"></span>
                        </div>
						
                    </div>
                </div>

                <div class="mb-2">
                    <button type="submit" class="btn btn-primary w-100">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
    // Set minimum date and time to current date and time, preventing selection of past dates and times
    const deliveryDateTimeInput = document.getElementById('deliveryDateTime');
    const now = new Date();
    const localDateTime = new Date(now.getTime() - now.getTimezoneOffset() * 60000).toISOString().slice(0, 16);
    deliveryDateTimeInput.min = localDateTime;
</script>

WebEcommerce/Areas/Admin/Views/Invoice/Index.cshtml
@using X.PagedList
@using X.PagedList.Mvc.Core
@model IPagedList<WebEcommerce.ViewModels.InvoiceVM>
@{
    ViewData["Title"] = "Danh sách hóa đơn";
}

<div class="container-fluid">
    <div class="card">
        <div class="card-header bg-primary">
            <h4 class="card-title text-white">Danh sách hóa đơn</h4>
        </div>
        <div class="card-body">
            <table class="table table-striped table-hover" id="myTable">
                <thead>
                    <tr>
                        <th>Mã đơn hàng</th>
                        <th>Họ</th>
                        <th>Tên</th>
                        <th>Số điện thoại</th>
                        <th>Email</th>
                        <th>Phương thức thanh toán</th>
                        <th>Ngày tạo</th>
                        <th>Ngày vận chuyển</th>
                        <th>Trạng thái</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var i in Model)
                    {
                        <tr>
                            
                            <td>@i.Code</td>
                            <td>@i.FirstName</td>
                            <td>@i.LastName</td>
                            <td>@i.PhoneNumber</td>
                            <td>@i.Email</td>
                            <td>@i.PaymentMethod</td>
                            <td>@i.OrderDate</td>
                            <td>@i.DeliveryDate</td>
                             <td>
                                 @if (i.StatusId == 1)
                                 {
                                     <span>Chưa thanh toán</span>
                                 }
                                @if (i.StatusId == 2)
                                 {
                                     <span>Đã thanh toán</span>
                                 }
                                @if (i.StatusId == 3)
                                 {
                                     <span>Hoàn thành</span>
                                 }
                                @if (i.StatusId == 4)
                                 {
                                     <span>Hủy</span>
                                 }
                             </td>
                            <td class="action-buttons">
                                <a class="btn btn-success btn-sm" asp-area="Admin" asp-controller="Invoice" asp-action="Detail" asp-route-id="@i.InvoiceDetailId">View</a>|

                                <a class="btn btn-warning btn-sm" asp-area="Admin" asp-controller="Invoice" asp-action="Edit" asp-route-id="@i.Id">Edit</a>|
                                <form class="d-inline" asp-area="Admin" asp-controller="Invoice" asp-action="Delete" asp-route-id="@i.Id" method="post" onsubmit="return confirm('Do you want to delete this invoice?')">
                                    <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                                </form>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <div class="card-footer">
            Page @(Model?.PageCount < Model?.PageNumber ? 0 : Model?.PageNumber) of @Model?.PageCount
            @Html.PagedListPager(Model, page => Url.Action("Index",
                     new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }),
                     new PagedListRenderOptions()
            {
                ContainerDivClasses = new List<string> { "invoice", "navigation" },
                UlElementClasses = new List<string> { "pagination" },
                LiElementClasses = new List<string> { "page-item", "page-link" },
                ActiveLiElementClass = "active",

            })
        </div>
    </div>
</div>